### ISSUE TITLE
Current Issues

### ISSUE THREAD

**Issue by ghost** [Rafase282/mangadb-front#10]
- [x] Fix padding on login page
- [x] The cards are way too big
- [x] Make alerts smaller

**Comment by Rafase282** [comment]
Fixed the size of the card, but the problem is the image in it.

**Comment by Rafase282** [comment]
I made the alerts. smaller, no more scaling for them.

**Comment by Rafase282** [comment]
This commit has all the fixes in it https://github.com/Rafase282/mangadb-front/commit/acc64c9775f2915130eb39d51a5609f08e6e184e
