### ISSUE TITLE
Fix Error Page

### ISSUE THREAD

**Issue by Rafase282** [Rafase282/mangadb-front#5]
Instead of sending the user to the error page and displaying the error template or a 404 the site crashes.

**Comment by theflametrooper** [comment]
I'll help with this!

**Comment by Rafase282** [comment]
Fixed with:
- https://github.com/Rafase282/mangadb-front/commit/4e1f83704da46193afca8358161ef8d7d2a9bc01
- https://github.com/Rafase282/mangadb-front/commit/e8745583bf81a490c7aedb2b0e89adcd2a408511
